// Packages build/ into template.zip, ready for the DSPLAY Web Manager. Pure Node (fs + archiver)
// on purpose — the previous build.sh needed bash plus the system `zip` CLI, neither of which
// ships on Windows (not even under Git Bash), so `npm run zip` simply didn't work there.
import { createWriteStream, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import archiver from 'archiver';

const buildDir = resolve('build');
const zipPath = resolve('template.zip');

rmSync(resolve(buildDir, 'test-assets'), { recursive: true, force: true });
rmSync(zipPath, { force: true });

// The DSPLAY Android app injects the real `window.DSPLAY.getData()` before any script runs, so
// this file's actual content is never read in production — it only needs to exist.
writeFileSync(resolve(buildDir, 'dsplay-data.js'), '// the content of this file will be generated by DSPLAY player\n');

const output = createWriteStream(zipPath);
const archive = archiver('zip');

output.on('close', () => console.log('template.zip generated with success!'));
archive.on('warning', (err) => { throw err; });
archive.on('error', (err) => { throw err; });

archive.pipe(output);
// `false` keeps build/'s contents at the zip root (index.html, assets/, ...) instead of nesting
// them under a `build/` folder inside the zip.
archive.directory(buildDir, false);
await archive.finalize();
